# Generated by Django 5.0.6 on 2024-08-04 10:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=1000)),
                ('Marks', models.IntegerField()),
                ('img_Solution', models.ImageField(blank=True, null=True, upload_to='Assests/Solutions/')),
                ('text_Solution', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=50)),
                ('Lname', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=8, null=True)),
                ('Age', models.IntegerField()),
                ('Contact', models.CharField(max_length=15)),
                ('Country', models.CharField(max_length=30, null=True)),
                ('State', models.CharField(max_length=50, null=True)),
                ('City', models.CharField(max_length=30, null=True)),
                ('Address', models.CharField(max_length=130, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('document', models.FileField(upload_to='Assests/Notes/')),
                ('Catagory', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Test.catagory')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer', models.CharField(max_length=100)),
                ('is_Correct', models.BooleanField(default=False)),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='Test.question')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, unique=True)),
                ('Start_at', models.DateTimeField(default=datetime.datetime(2024, 8, 4, 10, 3, 44, 466854, tzinfo=datetime.timezone.utc))),
                ('Timing', models.PositiveIntegerField()),
                ('num_Questions', models.PositiveIntegerField()),
                ('Total_Marks', models.PositiveIntegerField()),
                ('Catagory', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Test.catagory')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.answer')),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.question')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.student')),
                ('Test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.test')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Rank', models.PositiveIntegerField(null=True)),
                ('Total_Marks', models.IntegerField()),
                ('Obtained_Marks', models.IntegerField(null=True)),
                ('Total_Attempted', models.PositiveIntegerField()),
                ('Accuracy', models.FloatField()),
                ('Percentile', models.FloatField(null=True)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.student')),
                ('Test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.test')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='Test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='Test.test'),
        ),
        migrations.AddField(
            model_name='student',
            name='Email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.user'),
        ),
    ]
