# Generated by Django 5.0.6 on 2024-07-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Address',
            field=models.CharField(max_length=130, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='City',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Country',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Gender',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='State',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='Fname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='Lname',
            field=models.CharField(max_length=50),
        ),
    ]
