# Generated by Django 5.0.6 on 2024-08-04 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='Start_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 4, 10, 32, 54, 289283, tzinfo=datetime.timezone.utc)),
        ),
    ]
