# Generated by Django 5.0.6 on 2024-07-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0002_student_address_student_city_student_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Password',
            field=models.CharField(max_length=200),
        ),
    ]
