# Generated by Django 5.0.6 on 2024-07-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0005_question_answer_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='Name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
