# Generated by Django 5.0.6 on 2024-07-05 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0006_alter_test_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='Test.test'),
        ),
    ]
