# Generated by Django 5.0.6 on 2024-07-06 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0007_alter_question_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.answer')),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.question')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.student')),
                ('Test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.test')),
            ],
        ),
    ]
