# Generated by Django 5.0.6 on 2024-07-19 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0015_result_obtained_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='Start_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 19, 15, 55, 7, 2647, tzinfo=datetime.timezone.utc)),
        ),
    ]
