# Generated by Django 5.0.6 on 2024-07-21 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0016_test_start_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='Start_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 21, 11, 17, 51, 788913, tzinfo=datetime.timezone.utc)),
        ),
    ]
